CREATE TABLE usage_log_daily (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    stat_date DATE NOT NULL,
    api_key_id INT NULL,
    api_key_name VARCHAR(255) NULL,
    provider_config_id INT NULL,
    provider_name VARCHAR(255) NOT NULL,
    model_config_id INT NULL,
    model_name VARCHAR(255) NOT NULL,
    requests INT NOT NULL DEFAULT 0,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    cache_hit_tokens BIGINT NOT NULL DEFAULT 0,
    cache_miss_tokens BIGINT NOT NULL DEFAULT 0,
    avg_duration_ms INT NOT NULL DEFAULT 0,
    min_duration_ms INT NOT NULL DEFAULT 0,
    max_duration_ms INT NOT NULL DEFAULT 0,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_daily (stat_date, api_key_id, provider_config_id, model_config_id),
    INDEX idx_stat_date (stat_date),
    INDEX idx_provider_config_id (provider_config_id),
    INDEX idx_model_config_id (model_config_id),
    INDEX idx_api_key_id (api_key_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
